### ISSUE TITLE
RealSense D435 calibration parameters

### ISSUE THREAD

**Issue by kmfrick** [tu-darmstadt-ros-pkg/hector_models#7]
Are the calibration parameters (intrinsics and baseline) of the D435 (or any camera, really) the same as the real camera?

**Comment by Martin-Oehler** [comment]
No, calibration parameters are different for each individual camera.

**Comment by kmfrick** [comment]
Thank you. They can be found in the `camera_info` topic, right?

**Comment by kmfrick** [comment]
I tested the calibration parameters from that topic and they work.
