### ISSUE TITLE
What is the "xacro:inertial_sphere" in file "vlp16.urdf.xacro"?

### ISSUE THREAD

**Issue by NoRomantic** [tu-darmstadt-ros-pkg/hector_models#9]
I tried to add vlp16_model into our turtlebot2 robot. However, when I run this command, 
 `rosrun xacro xacro kobuki_hexagons_velodyne.urdf.xacro > ~/temp.xml` 

error came as below. I've search online but still can't figure out what "xacro:inertial_sphere" means. Anyone helps, please? BTW, the OS is ubuntu16 and ros version is kinect. Thanks!

> unknown macro name: xacro:inertial_sphere None None
> when instantiating macro: vlp16_model (kobuki_hexagons_velodyne.urdf.xacro) 
> in file: kobuki_hexagons_velodyne.urdf.xacro

**Comment by Martin-Oehler** [comment]
xacro:inertial_sphere is a xacro macro used inside the vlp16 macro. It is defined [here](https://github.com/tu-darmstadt-ros-pkg/hector_models/blob/kinetic-devel/hector_xacro_tools/urdf/inertia_tensors.urdf.xacro). Apparently, the include is missing. I added it in my recent commit.
